# Generated by Django 3.1.7 on 2021-03-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='x',
            field=models.FloatField(max_length=9),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='y',
            field=models.FloatField(max_length=9),
        ),
    ]
