# Generated by Django 3.1.7 on 2021-03-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20210307_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Y_coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.FloatField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='coordinate',
            name='y',
        ),
    ]
