# Generated by Django 3.1.7 on 2021-03-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_auto_20210307_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='y_coordinate',
            name='y',
            field=models.IntegerField(),
        ),
    ]
