# Generated by Django 3.1.7 on 2021-03-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_auto_20210307_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='y_coordinate',
            name='y',
            field=models.FloatField(),
        ),
    ]
